# x402-dev Configuration for MCP Server Starter
# This file configures the x402-dev daemon for payment processing

# Server Configuration
port: 8402
host: "127.0.0.1"

# Solana Network Configuration
# Use devnet for testing (free SOL from faucet)
# Switch to mainnet-beta for production
solana_rpc: "https://api.devnet.solana.com"

# Payment Settings
payment_amount: 1000          # Default payment in lamports (0.000001 SOL)
payment_timeout: 900          # Invoice expiration in seconds (15 minutes)

# Logging
log_level: "info"             # Options: debug, info, warn, error
log_file: "x402dev.log"

# Security
require_signature: true       # Verify payment signatures
allow_duplicate_payments: false  # Prevent payment reuse

# Rate Limiting (optional)
# rate_limit:
#   requests_per_minute: 60
#   burst_size: 10

# Webhook Notifications (optional)
# webhook:
#   url: "https://your-server.com/webhook/payment"
#   events: ["payment.success", "payment.failed"]

# Advanced Options
# cache_ttl: 3600              # Cache payment verifications (seconds)
# retry_attempts: 3            # Retry failed RPC calls
# connection_timeout: 30       # RPC connection timeout (seconds)
